name: Build the service of YT subtitles editing on VPS

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run a build command
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yml
          set-safe-directory: false
          directory: ${{secrets.LOCAL_APP_PATH}}/.ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: ${{secrets.INVENTORY}}
          options: |
            -e RELEASE=${{github.ref_name}}
            -e VPS_USER=${{secrets.VPS_USER}}
            -e VPS_APP_PATH=${{secrets.VPS_APP_PATH}}
            -e GITHUB_REPO=${{github.repository}}
